### ISSUE TITLE
Doesn't work with SonarCloud

### ISSUE THREAD

**Issue by acerrillobd** [simondel/sonar-buildbreaker-vsts#1]
Allways fails the build with the following message: Unhandled: Cannot read property 'analysisId' of undefined

**Comment by simondel** [comment]
Thanks for taking the time to try out the task and report this issue! I currently don't have any projects on SonarCloud so I did not test the support with that.

Could you go to: https://sonarcloud.io/api/ce/component?componentKey=YOUR_PROJECT_ID (replacing `YOUR_PROJECT_ID` with your id. You can find this when you go to your project (for example the id of https://sonarcloud.io/dashboard?id=Stryker.NET would be `Stryker.NET`). This will give you some json back which could look like this:
```json
{
   "queue":[

   ],
   "current":{
      "id":"AWMg4b3TOnVewt-wi1mP",
      "type":"REPORT",
      "componentId":"AWMguxWRXhRh5gha-KW4",
      "componentKey":"mesa-release",
      "componentName":"mesa-release",
      "componentQualifier":"TRK",
      "analysisId":"AWMg4d15fKfZeQj7IR5l",
      "status":"SUCCESS",
      "submittedAt":"2018-05-02T14:44:18+0200",
      "submitterLogin":"jasuarez@github",
      "startedAt":"2018-05-02T14:44:18+0200",
      "executedAt":"2018-05-02T14:49:54+0200",
      "executionTimeMs":335722,
      "logs":false,
      "hasScannerContext":true,
      "organization":"jasuarez-github"
   }
}
```
What you're looking for is the `id` property in the `current` object. In this case that's `"AWMg4b3TOnVewt-wi1mP"`.  With this id you can go to the URL https://sonarcloud.io/api/ce/task?id=AWMg4b3TOnVewt-wi1mP (replacing the ID with your id).

What does this last call return? 

I would expect something similar to:
```json
{  
   "task":{  
      "id":"AWOsPqlElnepFyfIDmYp",
      "type":"REPORT",
      "componentId":"AWH2DX6PfLczuMU3y_ZO",
      "componentKey":"MY_COMPONENT_KEY",
      "componentName":"MY_COMPONENT_NAME",
      "componentQualifier":"TRK",
      "analysisId":"AWOsPrFW6u2z4hkS9Gr-",
      "status":"SUCCESS",
      "submittedAt":"2018-05-29T16:12:57+0200",
      "submitterLogin":"MY_BUILD_USER",
      "startedAt":"2018-05-29T16:12:59+0200",
      "executedAt":"2018-05-29T16:13:05+0200",
      "executionTimeMs":6195,
      "logs":false,
      "hasScannerContext":true,
      "organization":"default-organization"
   }
}
```

I have updated the description of the extension for now to mention the lack of SonarCloud support

**Comment by acerrillobd** [comment]
I got this: 
```
{
    "task": {
        "id": "AWOxb1noCPImwYt77Bwl",
        "type": "REPORT",
        "componentId": "AWOs8lX4NPlZRTBE7nTz",
        "componentKey": "SonarQubeSample",
        "componentName": "SonarQubeSample",
        "componentQualifier": "TRK",
        "analysisId": "AWOxb1554fWm9CZEJxR_",
        "status": "SUCCESS",
        "submittedAt": "2018-05-30T16:24:14+0200",
        "submitterLogin": "alfredo.cerrillo@bestday.com@microsoft",
        "startedAt": "2018-05-30T16:24:15+0200",
        "executedAt": "2018-05-30T16:24:18+0200",
        "executionTimeMs": 2164,
        "logs": false,
        "hasScannerContext": true,
        "organization": "alfredo-cerrillo-bestday-com-mic"
    }
}
```

**Comment by simondel** [comment]
Thanks! I have updated the plugin to version `6.2.3` which includes authentication. Could you test if the plugin now works for you?

**Comment by melih154** [comment]
Just installed latest plugin to VSTS from https://marketplace.visualstudio.com/items?itemName=SimondeLang.sonar-buildbreaker

Still getting the same error message. 
`Unhandled: Cannot read property 'analysisId' of undefined`

Ps. I am working on a private Sonar project and checking the above URL via a new browser session returns below error message.

`{"errors":[{"msg":"Insufficient privileges"}]}`

**Comment by acerrillobd** [comment]
I'm working with a public sample, but still getting same message as @melih154

**Comment by remkoseelig** [comment]
Using VSTS and SonarQube 6.7.1 I the build/plugin fails with: "Cannot read property 'task' of undefined".

**Comment by simondel** [comment]
Thanks for hanging in there. I found the time to build a reproduction app and I managed to reproduce it using SonarCloud:
![image](https://user-images.githubusercontent.com/4221997/41818895-99d7e5d0-77b7-11e8-8ae0-4e6905cf30b0.png)
I'll take a look at what's going wrong.

**Comment by simondel** [comment]
I have fixed the issue with SonarCloud. In my extension I was unable to access the endpoint data that is set in the SonarCloud/SonarQube prepare task. I created a separate task for SonarCloud that requires an endpoint to be selected. I have tested this and it seems to work for me:
![image](https://user-images.githubusercontent.com/4221997/41819412-77d60d14-77c0-11e8-9b99-83c683c3af79.png)

@acerrillobd @melih154 Could you try this extension and let me know if it works? https://marketplace.visualstudio.com/items?itemName=SimondeLang.sonarcloud-buildbreaker

@remkoseelig I'll release an updated version for SonarQube later this week.

**Comment by melih154** [comment]
Works, many thanks.

**Comment by simondel** [comment]
@remkoseelig I have updated the SonarQube extensions. Please upgrade to version 7.x of the task and set your SonarQube endpoint in order to use authentication:
![image](https://user-images.githubusercontent.com/4221997/42156231-d07a1110-7dea-11e8-9b12-9b52e35f7f80.png)

Please let me know if this fixes your issues!

**Comment by nboeckmann** [comment]
Hey,

I'm having the same issue as @remkoseelig and I'm using the 7.x version. I'm still getting the same error message as he does: "Cannot read property 'task' of undefined".

I'm using SQ Server 6.7.1 and I can see in the access.log that the queries are made OK and that content is returned. I've also validated the output of the queries and they seem to be ok considering what you have written earlier in this post.

Do you have any idea what can be the reason for it?

Nils

**Comment by samdinesh86** [comment]
@simondel Superb work thanks for building it.
> Starting: Break build on quality gate failure
>*****************************************************************************
> Task         : SonarQube build breaker
> Description  : Break the build when the quality gate fails.
> Version      : 7.0.2
> Author       : Simon de Lang
> Help         : 
> 
> The quality gate has failed with status: ERROR
> ******************************************************************************
> Finishing: Break build on quality gate failure`

im using SonarQube Version: 6.7.1
what could be the reason for this issues, as the log or no information is displayed. only the message "ERROR" is not helping it would be great if you can add some description to the message. 
Also one more doubt, does this work with TFS builds / VSTS Builds

**Comment by simondel** [comment]
@nboeckmann Thanks for trying it out! Where in the build do you have the task right now? Also, do you have the 'publish quality gate result' in your build before you run the builbreaker? (It calls the same endpoint)

@samdinesh86 Thanks for the feedback! The message that you get indicates that everything went well in my extension, but your quality gate has the status 'ERROR'. What kind of message would be more useful to you? Something like this:
> The quality gate has the status 'ERROR'. Failing the build because of a failed quality gate.

**Comment by nboeckmann** [comment]
Hey @simondel,

I’ve tried it on both sides of the ‘Publish Quality Gate Result’. Where is it supposed to be?

Nils

**Comment by simondel** [comment]
@nboeckmann I would suggest placing the official SonarQube task in front of my task. Is the SonarQube task able to upload the quality gate result? Because that calls the same endpoint as my task.

**Comment by samdinesh86** [comment]
@simondel 
The error message means that there is an error which doesn't clearly mention it is on the extension or from SonarQube- 
Descriptive error message example
ERROR: SonarQube failed to generate Quality Gate. 
ERROR: Failed to read Quality Gate ( Error on the extension).

On the other note, I have tried placing the task after the publish quality gate task still it fails, I'm running this on TFS, not on VSTS. 
Does this plugin work on TFS?

**Comment by simondel** [comment]
@samdinesh86 the message `The quality gate has failed with status: ERROR` everything went well, but the extension noticed that your quality gate has the status 'error' for this analysis so you failed to pass the quality gate. I'll improve the logging this weekend. Thanks for the feedback!

@nboeckmann I'll create a separate issue for your problem.

**Comment by simondel** [comment]
@samdinesh86 I have improved the logging:
![image](https://user-images.githubusercontent.com/4221997/42407428-c8e4b146-81bc-11e8-99e6-6f296393587f.png)


I'll close this issue for now as the plugin seems to work just fine with SonarCloud. If anyone still has an issue or suggestion, feel free to open a new issue.
